#!/usr/bin/python3
# -*- coding: iso-8859-1 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#              C E D A R
#          S O L U T I O N S       "Software done right."
#           S O F T W A R E
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Author   : Kenneth J. Pronovici <pronovic@ieee.org>
# Language : Python 3 (>= 3.7)
# Project  : Cedar Backup, release 3
# Purpose  : Implements Cedar Backup cback3 script.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

"""
Implements Cedar Backup cback3 script.
@author: Kenneth J. Pronovici <pronovic@ieee.org>
"""

try:
   import sys
   from CedarBackup3.cli import cli
except ImportError as e:
   print("Failed to import Python modules: %s" % e)
   print("Are you running a proper version of Python?")
   sys.exit(1)

result = cli()
sys.exit(result)

