#!/bin/sh
# Script to restart the Mac OS X auto mount daemon once we're done using cdrtools.
# Swiped from online documentation related to X-CD-Roast and reformatted.
# Note: this daemon was apparently called autodiskmount in OS X 10.3 and prior.
sudo kill -CONT `ps -ax | grep diskarbitrationd | grep -v grep | sed -e 's/\([^\?]*\).*/\1/' `  
echo "Auto mount process ID `ps -ax | grep diskarbitrationd | grep -v grep | sed -e 's/\([^\?]*\).*/\1/' ` restarted." 
