#!/bin/ksh
# Sensibly creates a branch off a named release in Subversion.

REPO=https://cedar-backup.svn.sourceforge.net/svnroot/cedar-backup/cedar-backup2

if [[ $# != 2 || ${1} == "--help" ]]
then
   print "Usage: branch <version> <branchname>"
   exit 1
fi

VERSION=${1}
BRANCH=${2}

svn copy ${REPO}/tags/CEDAR_BACKUP2_V${VERSION} \
         ${REPO}/branches/${BRANCH} \
         -m "Branching version ${VERSION} to branch ${BRANCH}."
if [[ $? != 0 ]]
then
   print "Failed to create branch ${BRANCH}."
   exit 1
fi

print "Completed branching version ${VERSION} to branch ${BRANCH}:"
print ""

svn list --verbose ${REPO}/branches

print ""

