#!/bin/ksh
# Sensibly creates a release label in Subversion.

echo "You'll have to enter your SF password a lot of times, sorry"

REPO=svn+ssh://pronovic@svn.code.sf.net/p/cedar-backup/code/cedar-backup2

if [[ $# != 1 || ${1} == "--help" ]]
then
   print "Usage: release <version>"
   exit 1
fi

VERSION=${1}

svn list ${REPO}/tags/CEDAR_BACKUP2_V${VERSION} >/dev/null 2>&1
if [[ $? = 0 ]]
then
   print "Removing existing release label for ${VERSION}."
   svn del ${REPO}/tags/CEDAR_BACKUP2_V${VERSION} \
            -m "Tagging new version of ${VERSION} release of Cedar Backup."
fi

svn copy ${REPO}/trunk \
         ${REPO}/tags/CEDAR_BACKUP2_V${VERSION} \
         -m "Tagging the ${VERSION} release of Cedar Backup."
if [[ $? != 0 ]]
then
   print "Failed to label ${VERSION} release."
   exit 1
fi

print "Completed tagging release ${VERSION} of Cedar Backup:"
print ""

svn list --verbose ${REPO}/tags | $(dirname $0)/sorttags.py

print ""
print "Make sure to re-run this script if you forgot to update"
print "the Changelog or CedarBackup2/release.py!"
print ""

