#!/bin/ksh
# Runs the validating onsgmls processor against the indicated XML file.

# The onsgmls processor is a replacement for ngsgmls. In Debian, it's
# found in the opensp package.

# This line is always printed, so I try to filter it out.
# osgmls:/usr/share/xml/declaration/xml.dcl:1:W: SGML declaration was not implied

SOC="/usr/share/xml/declaration/xml.soc"
DECL="/usr/share/xml/declaration/xml.dcl"
SP_CHARSET_FIXED=YES SP_ENCODING=XML onsgmls -wxml -m${SOC} -ges ${DECL} $* 2>&1 | grep -v '^onsgmls.*xml\.dcl:1:W:' | grep -v '^onsgmls:.*xml\.dcl:31:27:W:'
exit 0
