echo "To run scripts, use UV directly: "
echo ""
echo "- uv run cback3"
echo "- uv run cback3-amazons3-sync"
echo "- uv run cback3-span"
echo ""
echo "These are the exact scripts published by UV as part of the Python package."
echo ""
